name: LotteryTicket
authors: ['Bryan_lzh']
main: Br.LotteryTicket.Main
version: 2.0
depend: [Vault,BrAPI]

commands:
  LotteryTicket:
    aliases: [lt,彩票]
    description: 主命令
    usage: /<command> help